source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CCAdition_Example', :exclusive => true do
  pod "CCAdition", :path => "../"
end

target 'CCAdition_Tests', :exclusive => true do
  pod "CCAdition", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
